'use client';

import React, { useState } from 'react';
import { Bot, Send, AlertCircle, Database, CheckCircle2, Clock } from 'lucide-react';

export default function OpenClawTester() {
    const [payload, setPayload] = useState('');
    const [endpoint, setEndpoint] = useState('/api/admin/blogs');
    const [method, setMethod] = useState('POST');
    const [response, setResponse] = useState<any>(null);
    const [loading, setLoading] = useState(false);
    const [activeTab, setActiveTab] = useState<'blogs' | 'products' | 'social'>('blogs');

    const templates = {
        blogs: {
            endpoint: '/api/admin/blogs',
            method: 'POST',
            payload: JSON.stringify({
                title: "Top 5 Auto Litter Boxes Evaluated by AI",
                slug: "top-5-auto-litter-boxes-" + Date.now(),
                content: "## The Evolution of Litter Boxes\n\nAI analysis shows automated boxes save 14 hours a month...",
                excerpt: "An AI-driven analysis of the best auto litter boxes of the year.",
                coverImage: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba",
                tags: ["AI Review", "Tech", "Cats"],
                metadata: {
                    seoTitle: "AI Rated Best Auto Litter Boxes",
                    seoDescription: "Discover the top 5 self-cleaning litter boxes determined by deep data analysis."
                }
            }, null, 2)
        },
        products: {
            endpoint: '/api/admin/products',
            method: 'POST',
            payload: JSON.stringify({
                name: "AI Generated Litter Robot Case",
                slug: "ai-generated-case-" + Date.now(),
                price: 49.99,
                category: "Accessories",
                description: "This is a dummy product generated by the OpenClaw integration test.",
                features: ["AI Designed", "Durable", "Easy to clean"],
                images: ["https://images.unsplash.com/photo-1495360010541-f48722b34f7d"],
                amazonLink: "https://amazon.com/dp/B0TESTAILINK"
            }, null, 2)
        },
        social: {
            endpoint: '/api/admin/social/publish',
            method: 'POST',
            payload: JSON.stringify({
                platform: "pinterest",
                content: "Check out our ultimate guide strictly written by an AI Agent on feline health! 🐈🌟 #cats",
                mediaUrl: "https://images.unsplash.com/photo-1543852786-1cf6624b9987",
                link: "https://autolitterboxpro.com/blog/example-ai",
                boardId: "your-board-id"
            }, null, 2)
        }
    };

    const handleTabChange = (tab: 'blogs' | 'products' | 'social') => {
        setActiveTab(tab);
        setEndpoint(templates[tab].endpoint);
        setMethod(templates[tab].method);
        setPayload(templates[tab].payload);
        setResponse(null);
    };

    const runSimulation = async () => {
        const adminPass = sessionStorage.getItem('admin-auth');
        if (!adminPass) {
            setResponse({ error: "No admin authentication found in session." });
            return;
        }

        setLoading(true);
        setResponse(null);

        try {
            let options: RequestInit = {
                method: method,
                headers: {
                    'Authorization': `Bearer ${adminPass}`,
                    'Content-Type': 'application/json'
                }
            };
            
            if (method !== 'GET') {
                options.body = payload;
            }

            const start = Date.now();
            const res = await fetch(endpoint, options);
            const data = await res.json().catch(() => ({ raw: "Empty or invalid JSON body returned" }));
            const duration = Date.now() - start;

            setResponse({
                status: res.status,
                ok: res.ok,
                durationMs: duration,
                data: data
            });
        } catch (err: any) {
            setResponse({ error: err.message, status: 500 });
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="max-w-5xl mx-auto">
            <div className="mb-8">
                <div className="flex items-center gap-4 mb-2">
                    <div className="w-12 h-12 bg-[#2D6A44] rounded-2xl flex items-center justify-center shadow-lg">
                        <Bot className="w-6 h-6 text-white" />
                    </div>
                    <div>
                        <h1 className="text-3xl font-bold text-text-primary">OpenClaw Sandbox</h1>
                        <p className="text-text-muted mt-1">Joint Debugging & Automation Simulator Interface</p>
                    </div>
                </div>
                <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 flex items-start gap-3 mt-6">
                    <AlertCircle className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
                    <p className="text-sm text-blue-800">
                        Use this sandbox to trigger the exact same APIs that OpenClaw will use. 
                        It automatically injects your <strong>Bearer Authentication Password</strong>. 
                        Modify the JSON payload to simulate different Agent behaviors.
                    </p>
                </div>
            </div>

            <div className="grid lg:grid-cols-2 gap-8">
                {/* Left Panel: Request Builder */}
                <div className="bg-white rounded-2xl shadow-sm border border-[#E5E4E1] p-6 flex flex-col h-full">
                    <h2 className="text-lg font-bold text-text-primary border-b border-[#E5E4E1] pb-4 mb-4 flex items-center justify-between">
                        Configuration
                        <span className="flex text-xs font-medium bg-surface-bg rounded-lg p-1">
                            <button onClick={() => handleTabChange('blogs')} className={`px-3 py-1.5 rounded-md transition-colors ${activeTab === 'blogs' ? 'bg-white shadow-sm text-primary-600' : 'text-text-muted hover:text-text-primary'}`}>Blogs</button>
                            <button onClick={() => handleTabChange('products')} className={`px-3 py-1.5 rounded-md transition-colors ${activeTab === 'products' ? 'bg-white shadow-sm text-primary-600' : 'text-text-muted hover:text-text-primary'}`}>Products</button>
                            <button onClick={() => handleTabChange('social')} className={`px-3 py-1.5 rounded-md transition-colors ${activeTab === 'social' ? 'bg-white shadow-sm text-primary-600' : 'text-text-muted hover:text-text-primary'}`}>Social</button>
                        </span>
                    </h2>

                    <div className="space-y-4 flex-1 flex flex-col">
                        <div>
                            <label className="block text-xs font-bold text-text-muted uppercase mb-1">Target Endpoint</label>
                            <div className="flex bg-surface-bg rounded-xl border border-[#E5E4E1] overflow-hidden">
                                <span className="bg-[#E5E4E1] px-4 py-3 font-mono text-sm text-text-secondary font-bold border-r border-[#D1D0CD]">
                                    {method}
                                </span>
                                <input 
                                    type="text" 
                                    value={endpoint} 
                                    onChange={(e) => setEndpoint(e.target.value)} 
                                    className="flex-1 bg-transparent px-4 py-3 font-mono text-sm focus:outline-none focus:ring-1 focus:ring-primary-600"
                                />
                            </div>
                        </div>

                        <div className="flex-1 flex flex-col">
                            <label className="flex text-xs font-bold text-text-muted uppercase mb-1 justify-between">
                                Request Payload (JSON)
                                <button 
                                    onClick={() => setPayload(templates[activeTab].payload)}
                                    className="text-primary-600 hover:text-[#2D6A44]"
                                >Reset to Template</button>
                            </label>
                            <textarea
                                value={payload}
                                onChange={(e) => setPayload(e.target.value)}
                                className="w-full flex-1 bg-text-primary text-[#E5E4E1] font-mono text-sm p-4 border border-[#E5E4E1] rounded-xl focus:outline-none focus:border-primary-600 min-h-[300px]"
                                spellCheck={false}
                            />
                        </div>

                        <button
                            onClick={runSimulation}
                            disabled={loading}
                            className="w-full mt-4 flex justify-center items-center gap-2 py-4 bg-[#2D6A44] hover:bg-[#1f4a2f] disabled:opacity-50 text-white font-bold rounded-xl transition-all shadow-lg"
                        >
                            {loading ? (
                                <span className="animate-spin w-5 h-5 border-2 border-white border-t-transparent rounded-full" />
                            ) : (
                                <>
                                    <Send className="w-5 h-5" />
                                    Fire OpenClaw Payload
                                </>
                            )}
                        </button>
                    </div>
                </div>

                {/* Right Panel: Response Output */}
                <div className="bg-white rounded-2xl shadow-sm border border-[#E5E4E1] flex flex-col h-full overflow-hidden">
                    <div className="p-6 border-b border-[#E5E4E1] bg-surface-bg flex items-center justify-between">
                        <h2 className="text-lg font-bold text-text-primary flex items-center gap-2">
                            <Database className="w-5 h-5 text-text-muted" />
                            Live Feedback
                        </h2>
                        {response && response.status && (
                            <div className="flex items-center gap-4 text-xs font-bold">
                                <span className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full ${response.ok ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                                    {response.ok ? <CheckCircle2 className="w-4 h-4" /> : <AlertCircle className="w-4 h-4" />}
                                    Status: {response.status}
                                </span>
                                <span className="flex items-center gap-1 text-text-muted bg-white border border-[#E5E4E1] px-2 py-1.5 rounded-lg shadow-sm">
                                    <Clock className="w-3.5 h-3.5" />
                                    {response.durationMs} ms
                                </span>
                            </div>
                        )}
                    </div>
                    
                    <div className="flex-1 bg-[#0A0A0A] p-6 overflow-auto">
                        {!response ? (
                            <div className="h-full flex flex-col items-center justify-center text-[#666]">
                                <Bot className="w-16 h-16 mb-4 opacity-20" />
                                <p className="font-mono text-sm">Awaiting simulation trigger...</p>
                            </div>
                        ) : (
                            <pre className="text-green-400 font-mono text-xs whitespace-pre-wrap">
                                {JSON.stringify(response.data || response.error, null, 2)}
                            </pre>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
